bools_to_add = [
'L_Arm_Flip_IK',
'L_Arm_IK',
'L_Foot_Flip',
'L_Hand_Flip',
'L_Hand_Nudge',
'L_Leg_Flip_IK',
'L_Leg_IK',
'R_Arm_Flip_IK',
'R_Arm_IK',
'R_Arm_IK_Flip',
'R_Arm_Leg_IK',
'R_Foot_Flip',
'R_Hand_Flip',
'R_Hand_Nudge',
'R_Leg_Flip_IK',
'R_Leg_IK',
]



tiny_media_bones_legend = {
"MASTER": "Global.Location",
"Leg.R.Position": "R_Leg_Nudge",
"\Leg.R.Up": "R_Leg.Up",
"Leg.R.Lw": "R_Leg.Lw",
"Leg.R.POLE": "R_Leg_Pole",
"Leg.L.Position": "L_Leg_Nudge",
"Leg.L.POLE": "L_Leg_Pole",
"Leg.L.Up": "L_Leg.Up",
"Leg.L.Lw": "L_Leg.Lw",
"Eyelid.L.Up.M": "L_Eyelid.Up.M",
"Eyelid.L.Lw.M": "L_Eyelid.Lw.M",
"Eyelid.R.Lw.M": "R_Eyelid.Lw.M",
"Eyelid.R.Up.M": "R_Eyelid.Up.M",
"Eyebrow.R.Up.M": "R_Eyebrow.Up.M",
"Eyebrow.L.Up.M.001": "L_Eyebrow.Up.M",
"Arm.L.Position": "L_Arm_Nudge",
"Arm.L.Up": "L_Arm.Up",
"Arm.L.Lw": "L_Arm.Lw",
"Arm.L.Cuff": "L_Arm.Cuff",
"Arm.L.IK": "L_Arm_IK",
"Arm.L.POLE": "L_Arm_Pole",
"Arm.R.Position": "R_Arm_Nudge",
"Arm.R.Up": "R_Arm.Up",
"Arm.R.Lw": "R_Arm.Lw",
"Arm.R.Cuff": "R_Arm.Cuff",
"Arm.R.IK": "R_Arm_IK",
"Arm.R.POLE": "R_Arm_Pole",
"Leg.R.IK": "R_Leg_IK",
"Leg.L.IK": "L_Leg_IK",
"Leg.R.Foot": "R_Leg.Foot",
"Leg.L.Foot": "L_Leg.Foot",
"Arm.L.Hand": "L_Arm.Hand",
"Arm.R.Hand": "R_Arm.Hand",
"IK.Arm.L": "L_Arm_IK",
"IK.Arm.R": "R_Arm_IK",
"IK.Leg.L": "L_Leg_IK",
"IK.Leg.R": "R_Leg_IK",
}


bone_groups = {
'Left':'THEME03',
'Right':'THEME01',
'Face Bones':'THEME04',
'Body Bones':'THEME09',
'Eye AIm':'THEME02',
'Eye Lids':'THEME04',
'Eye Brows':'THEME03',
}

tiny_media_bone_groups = {
'Location': 'Body Bones', 
'Lower': 'Body Bones', 
'R_Leg_Nudge': 'Right', 
'R_Leg.Up': 'Right', 
'R_Leg.Lw': 'Right', 
'R_Leg_Pole': 'Right', 
'L_Leg_Nudge': 'Left', 
'L_Leg_Pole': 'Left', 
'L_Leg.Up': 'Left', 
'L_Leg.Lw': 'Left', 
'Upper': 'Body Bones', 
'Neck': 'Body Bones', 
'Eye_Aim.001': 'Body Bones', 
'Eye_Aim': 'Eye AIm',
'Eye.R.ctrl': 'Eye AIm', 
'Eye.L.ctrl': 'Eye AIm', 
'L_Eyelid.Up.M.001': 'Eye Lids', 
'R_Eyelid.Up.M.001': 'Face Bones', 
'L_Eyelid.Lw.M.001': 'Eye Lids',
'R_Eyelid.Lw.M.001': 'Eye Lids', 
'R_Eyebrow.Up.M.001': 'Eye Brows', 
'L_Eyebrow.Up.M.001': 'Eye Brows', 
'L_Arm_Nudge': 'Left', 
'L_Arm.Up': 'Left', 
'L_Arm.Lw': 'Left', 
'L_Arm.Cuff': 'Left', 
'L_Arm_IK': 'Left', 
'L_Arm_Pole': 'Left', 
'R_Arm_Nudge': 'Right', 
'R_Arm.Up': 'Right', 
'R_Arm.Lw': 'Right', 
'R_Arm.Cuff': 'Right', 
'R_Arm_IK': 'Right', 
'R_Arm_Pole': 'Right', 
'R_Leg_IK': 'Right', 
'L_Leg_IK': 'Left', 
'R_Leg.Foot': 'Right', 
'L_Arm.Hand': 'Left', 
'R_Arm.Hand': 'Right',     
}

tiny_lw_bones = [
    "R_Arm.Lw",
    "L_Arm.Lw",
    "R_Leg.Lw",
    "L_Leg.Lw",
]

tiny_hand_foot_bones = [
    "R_Arm.Hand",
    "L_Arm.Hand",
    "R_Leg.Foot",
    "L_Leg.Foot",
]